name: abdo_omar_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  diamond_bottom_bar: ^1.0.0
  provider: ^6.0.4
  percent_indicator: ^4.2.2
  font_awesome_flutter: ^10.2.1
  convex_bottom_bar: ^3.1.0+1
  horizontal_data_table: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - images/gehad.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source San Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf